---
# Create Domain in Digitalocean Account
- name: Create Domain in Digitalocean
  community.digitalocean.digital_ocean_domain:
    state: "{{ item.state }}"
    name: "{{ item.domain }}"
    oauth_token: "{{ do_oauth_token }}"
    ip: "{{ item.default_ip }}"

# Create / Update / Delete records
- include_tasks: record.yml
  with_items: "{{ item.entries }}"
  loop_control:
    loop_var: entry
    # Add pause as we are too fast for DO API
    pause: 1