- name: Create {{ entry.type | default('A')}} record for {{ entry.name }}
  community.digitalocean.digital_ocean_domain_record:
    oauth_token: "{{ do_oauth_token }}"
    state: "{{ entry.state | default('present')}}"
    domain: "{{ item.domain}}"
    type: "{{ entry.type | default('A')}}"
    name: "{{ entry.name }}"
    data: "{{ entry.data }}"
    ttl: 300